### ISSUE TITLE
st compilation error -  gd.h: No such file or directory

### ISSUE THREAD

**Issue by yuneguy** [bubstance/suckless#1]
``` % sudo make clean install
rm -f st.o x.o boxdraw.o hb.o st-0.9.tar.gz *.rej *.orig *.o
c99 -I/usr/X11R6/include `pkg-config --cflags fontconfig ` `pkg-config --cflags freetype2 ` `pkg-config --cflags harfbuzz ` -DVERSION=\"0.9\" -DICON=\"/usr/local/share/pixmaps/st.png\" -D_XOPEN_S
OURCE=600 -O1 -c st.c
In file included from st.c:20:
st.h:6:10: fatal error: gd.h: No such file or directory
    6 | #include <gd.h>
      | ^~~~~~
compile aborted.
make: *** [Makefile:22: st.o] Error 1
``` 

I am not good at this, please help me.

**Comment by bubstance** [comment]
Hey there, sorry I missed this issue; I don't get push notifications and I've been dealing with some family medical issues.

I'm glad you got the `gd` part figured out. I'd recommend checking the `config.def.h` for the keybindings as well as what programs I typically install, as I neglected to add a proper dependency list to this repo.

Any other questions or issues and I'll be more than happy to help out as much as I can.

Cheers,
-K.
